name: AP
favicon: null
layout_spectrum: 0.79523
typography_spectrum: 0.74532
title: Alexander Proudfoot Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#005d47'
    - '#442578'
    - '#d7812c'
    - '#e7ba8c'
  brandStrength: 0.5
  lightness: 0.8501165767665952
  saturation: 0.3125
  rhythmicContrast: 0.6375519626308233
purpose: []
