name: AP
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2921147
title: Alexander Proudfoot Blog
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#005d47'
    - '#442578'
    - '#d7812c'
    - '#e7ba8c'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
