name: AP
favicon: null
layout_spectrum: 0.18421287089586258
typography_spectrum: 0.054174538934603333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8760384821798652
  lightness: 0.8501165767665952
  saturation: 0.35755413165315986
  rhythmicContrast: 0.6375519626308233
purpose: []
