title: Alexander Proudfoot Blog
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.25
  brandStrength: 0.01971326
  lightness: 0.75
  brandColors:
    - '#ffffff'
    - '#005d47'
    - '#442578'
    - '#d7812c'
    - '#e7ba8c'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: AP
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2921147
layout_spectrum: 1
